version: '3'
services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USERNAME=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_HOST=db
    networks:
      - ducklab-network


  ref:
    build:
      context: ./ref
      dockerfile: Dockerfile
    volumes:
      - ./ref:/var/www/html
    ports:
      - "8002:80"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=laravel2
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    networks:
      - ducklab-network

  # api:
  #   build:
  #     context: ./api
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ./api:/var/www/html
  #   ports:
  #     - "8000:80"
  #   depends_on:
  #     - db
  #   environment:
  #     - DB_HOST=db
  #     - DB_PORT=3306
  #     - DB_DATABASE=${DB_DATABASE}
  #     - DB_USERNAME=${DB_USERNAME}
  #     - DB_PASSWORD=${DB_PASSWORD}
  #   networks:
  #     - ducklab-network
  
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - ./app:/var/www/html
    ports:
      - "8801:80"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    networks:
      - ducklab-network

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    volumes:
      - ./web:/var/www/html
    ports:
      - "8800:80"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    networks:
      - ducklab-network
  


  db:
    image: mysql:8.0
    volumes:
      - db_data:/var/lib/mysql
      - ./web/ducklab.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
    networks:
      - ducklab-network

networks:
  ducklab-network:
    driver: bridge

volumes:
  db_data: