version: '3.8'
services:
  # nginx:
  #     image: nginx:latest  # Or specific Nginx version
  #     ports:
  #       - "81:80"  # Map host port 80 to container port 80 (default Nginx)
  #     volumes:
  #       - ./nginx.conf:/etc/nginx/nginx.conf:ro  # Optional: Mount custom Nginx config
  #     depends_on:
  #       - web

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USERNAME=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_HOST=db
    networks:
      - ducklab-network

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    volumes:
      - ./web:/var/www/html
    ports:
      - "8800:80"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    networks:
      - ducklab-network

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./api:/var/www/html
    ports:
      - "8801:3000"
    tty: true
    stdin_open: true
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    networks:
      - ducklab-network

  portal:
    build:
      context: ./portal
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    volumes:
      - ./portal:/app:rw 
    ports:
      - "8802:3000"
    depends_on:
      - db
    environment:
      - API_URL=http://api:3000
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - NODE_ENV=development
    command: npm run dev
    networks:
      - ducklab-network
  

  db:
    image: mysql:8.0
    volumes:
      - db_data:/var/lib/mysql
      - ./web/ducklab.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
    networks:
      - ducklab-network

networks:
  ducklab-network:
    driver: bridge

volumes:
  db_data: